version: '3.8'

services:
  api:
    build:
      context: ./deployment/api
      dockerfile: Dockerfile
    container_name: api_service
    volumes:
      - ./model:/app/model  # Mount the model directory for API access
    ports:
      - "8000:8000"

  app:
    build:
      context: ./deployment/app
      dockerfile: Dockerfile
    container_name: app_service
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000  # Use the service name as hostname
    ports:
      - "8501:8501"
